# Generated by Django 5.2.5 on 2025-08-22 15:27

import accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='todouser',
            managers=[
                ('objects', accounts.managers.ToDoManager()),
            ],
        ),
    ]
