# Generated by Django 5.2.5 on 2025-08-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accomplished_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending')], default='pending')),
            ],
        ),
    ]
