# Generated by Django 5.2.5 on 2025-08-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='accomplished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
