# Generated by Django 5.2.5 on 2025-08-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_by',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
