# Generated by Django 5.2.5 on 2026-04-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_task_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[("completed", "Completed"), ("pending", "Pending")],
                default="pending",
                max_length=100,
            ),
        ),
    ]
